services:
  chatbot:
    volumes:
      - ./data:/app/data
    develop:
      watch:
        - action: rebuild
          path: ./app
        - action: rebuild
          path: ./docker-compose.dev.yml
        - action: rebuild
          path: ./docker-compose.yml
    networks:
      - devnet
