services:
  chatbot:
    build: .
    container_name: chatbot-service
    image: chatbot-service
    env_file:
      - ./.env
    ports:
      - ${SERVICE_API_PORT:-8000}:8000
    volumes:
      - ./data/:/app/data/
      - ./logs/:/app/logs/
